#pragma once

#define SERVER_NAME L"fydbg"
#define DRVIER_NAME L"\\Device\\fydbg"
#define SYMBOL_LINK_NANM L"\\??\\fydbg"

struct SYSTEM_CALL_PARAM
{
	ULONG64 ssdt_index;
	ULONG64 args[0x10];
};
#define IO_CODE_SYSTEM_CALL CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_OUT_DIRECT,FILE_READ_DATA | FILE_WRITE_DATA)
struct FORWARD_EXCEPTION_PARAM
{
	union
	{
		PEXCEPTION_RECORD ExceptionRecord;
		PEXCEPTION_RECORD32 pExceptionRecord32;
	};
	union
	{
		PCONTEXT pContext;
		PWOW64_CONTEXT pWow64Context;
	};
	BOOLEAN First;
};
#define IO_CODE_FORWARD_EXCEPTION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_OUT_DIRECT,FILE_READ_DATA | FILE_WRITE_DATA)